services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - /.docker/postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - /.docker/rabbitmq/log/:/var/log/rabbitmq
